ALTER TABLE live_events.a_person DROP FOREIGN KEY fk_a_person_1;
ALTER TABLE live_events.a_person DROP FOREIGN KEY fk_a_person_2;
ALTER TABLE live_events.activity DROP FOREIGN KEY fk_activity_1;
ALTER TABLE live_events.c_address DROP FOREIGN KEY fk_c_address_address1;
ALTER TABLE live_events.c_address DROP FOREIGN KEY fk_c_address_person1;
ALTER TABLE live_events.c_address DROP FOREIGN KEY fk_c_address_post1;
ALTER TABLE live_events.p_citi DROP FOREIGN KEY fk_p_citi_citizenship1;
ALTER TABLE live_events.p_citi DROP FOREIGN KEY fk_p_citi_person;
ALTER TABLE live_events.p_edu DROP FOREIGN KEY fk_p_edu_education1;
ALTER TABLE live_events.p_edu DROP FOREIGN KEY fk_p_edu_person1;
ALTER TABLE live_events.p_email DROP FOREIGN KEY fk_p_email_person1;
ALTER TABLE live_events.p_phone DROP FOREIGN KEY fk_p_phone_person1;
ALTER TABLE live_events.p_stat DROP FOREIGN KEY fk_p_stat_person1;
ALTER TABLE live_events.p_stat DROP FOREIGN KEY fk_p_stat_statement1;
TRUNCATE TABLE live_events.a_person;
TRUNCATE TABLE live_events.activity;
TRUNCATE TABLE live_events.address;
TRUNCATE TABLE live_events.c_address;
TRUNCATE TABLE live_events.citizenship;
TRUNCATE TABLE live_events.commune;
TRUNCATE TABLE live_events.education;
TRUNCATE TABLE live_events.errors;
TRUNCATE TABLE live_events.p_citi;
TRUNCATE TABLE live_events.p_edu;
TRUNCATE TABLE live_events.p_email;
TRUNCATE TABLE live_events.p_phone;
TRUNCATE TABLE live_events.p_stat;
TRUNCATE TABLE live_events.person;
TRUNCATE TABLE live_events.post;
TRUNCATE TABLE live_events.statement;
TRUNCATE TABLE live_events.theme;
OPTIMIZE TABLE live_events.a_person;
OPTIMIZE TABLE live_events.activity;
OPTIMIZE TABLE live_events.address;
OPTIMIZE TABLE live_events.c_address;
OPTIMIZE TABLE live_events.citizenship;
OPTIMIZE TABLE live_events.commune;
OPTIMIZE TABLE live_events.education;
OPTIMIZE TABLE live_events.errors;
OPTIMIZE TABLE live_events.p_citi;
OPTIMIZE TABLE live_events.p_edu;
OPTIMIZE TABLE live_events.p_email;
OPTIMIZE TABLE live_events.p_phone;
OPTIMIZE TABLE live_events.p_stat;
OPTIMIZE TABLE live_events.person;
OPTIMIZE TABLE live_events.post;
OPTIMIZE TABLE live_events.statement;
OPTIMIZE TABLE live_events.theme;
ALTER TABLE live_events.a_person ADD CONSTRAINT fk_a_person_1 FOREIGN KEY(activity_id) REFERENCES activity(id);
ALTER TABLE live_events.a_person ADD CONSTRAINT fk_a_person_2 FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.activity ADD CONSTRAINT fk_activity_1 FOREIGN KEY(theme_id) REFERENCES theme(id);
ALTER TABLE live_events.c_address ADD CONSTRAINT fk_c_address_address1 FOREIGN KEY(address_id) REFERENCES address(id);
ALTER TABLE live_events.c_address ADD CONSTRAINT fk_c_address_person1 FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.c_address ADD CONSTRAINT fk_c_address_post1 FOREIGN KEY(post_id) REFERENCES post(id);
ALTER TABLE live_events.p_citi ADD CONSTRAINT fk_p_citi_citizenship1 FOREIGN KEY(citizenship_id) REFERENCES citizenship(id);
ALTER TABLE live_events.p_citi ADD CONSTRAINT fk_p_citi_person FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.p_edu ADD CONSTRAINT fk_p_edu_education1 FOREIGN KEY(education_id) REFERENCES education(id);
ALTER TABLE live_events.p_edu ADD CONSTRAINT fk_p_edu_person1 FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.p_email ADD CONSTRAINT fk_p_email_person1 FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.p_phone ADD CONSTRAINT fk_p_phone_person1 FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.p_stat ADD CONSTRAINT fk_p_stat_person1 FOREIGN KEY(person_id) REFERENCES person(id);
ALTER TABLE live_events.p_stat ADD CONSTRAINT fk_p_stat_statement1 FOREIGN KEY(statement_id) REFERENCES statement(id);
